# Generated by Django 3.1 on 2020-09-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(default='', max_length=200)),
                ('primarycontact', models.CharField(default='Mr', max_length=200)),
                ('first_name', models.CharField(default='', max_length=200)),
                ('last_name', models.CharField(default='', max_length=200)),
                ('company_name', models.CharField(default='', max_length=200)),
                ('display_name', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(default='', max_length=254)),
                ('work_phone_no', models.CharField(default='', max_length=15)),
                ('mobile_phone_no', models.CharField(default='', max_length=15)),
                ('designation', models.CharField(default='', max_length=200)),
                ('dept', models.CharField(default='', max_length=200)),
                ('website', models.CharField(default='', max_length=200)),
                ('gst_treatment', models.CharField(default='', max_length=200)),
                ('gst_id', models.CharField(default='', max_length=200)),
                ('place_of_supply', models.CharField(default='', max_length=200)),
                ('tax_prefrence', models.CharField(default='', max_length=200)),
                ('currency', models.CharField(default='', max_length=200)),
                ('payment_terms', models.CharField(default='', max_length=200)),
                ('billing_attention', models.CharField(default='', max_length=200)),
                ('billing_country', models.CharField(default='', max_length=200)),
                ('billing_address', models.CharField(default='', max_length=200)),
                ('billing_city', models.CharField(default='', max_length=200)),
                ('billing_state', models.CharField(default='', max_length=200)),
                ('billing_zipcode', models.CharField(default='', max_length=15)),
                ('billing_phone', models.CharField(default='', max_length=15)),
                ('billing_fax', models.CharField(default='', max_length=15)),
                ('shipping_attention', models.CharField(default='', max_length=200)),
                ('shipping_country', models.CharField(default='', max_length=200)),
                ('shipping_address', models.CharField(default='', max_length=200)),
                ('shipping_city', models.CharField(default='', max_length=200)),
                ('shipping_state', models.CharField(default='', max_length=200)),
                ('shipping_zipcode', models.CharField(default='', max_length=15)),
                ('shipping_phone', models.CharField(default='', max_length=15)),
                ('shipping_fax', models.CharField(default='', max_length=15)),
                ('organisation', models.CharField(default=' ', max_length=200)),
            ],
        ),
    ]
