# Generated by Django 3.1 on 2020-08-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200825_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='enable_portal',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='opening_balance',
            field=models.CharField(max_length=200),
        ),
    ]
