# Generated by Django 3.1 on 2020-08-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20200826_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='primarycontact',
            field=models.CharField(default='Mr', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='enable_portal',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
