# Generated by Django 3.0.8 on 2020-09-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20200921_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AddField(
            model_name='customer',
            name='oragnisation',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
