# Generated by Django 3.0.8 on 2020-09-25 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20200925_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='oragnisation',
            new_name='organisation',
        ),
    ]
