# Generated by Django 3.1 on 2020-09-27 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20200925_1856'),
        ('customer', '0005_auto_20200829_1519'),
    ]

    operations = [
    ]
