# Generated by Django 3.0.8 on 2020-09-29 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200929_1306'),
        ('customer', '0007_merge_20200927_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='billing_fax',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='billing_phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='billing_zipcode',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile_phone_no',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='customer',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Organisation'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='shipping_fax',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='shipping_phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='shipping_zipcode',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='work_phone_no',
            field=models.CharField(default='', max_length=15),
        ),
    ]
