# Generated by Django 3.1 on 2020-09-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_date', models.CharField(max_length=50)),
                ('estimate_number', models.CharField(max_length=100)),
                ('ref_number', models.CharField(max_length=250)),
                ('customer_name', models.CharField(max_length=200)),
                ('estimate_status', models.CharField(max_length=100)),
                ('estimate_amount', models.FloatField()),
            ],
        ),
    ]
