# Generated by Django 3.0.8 on 2020-09-16 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='estimate_amount',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='estimate_number',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='estimate_status',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='ref_number',
        ),
        migrations.AddField(
            model_name='estimate',
            name='adjustments',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='estimate',
            name='attach_file',
            field=models.FileField(default='', upload_to='file'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='billingAddress',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='estimate',
            name='cgst',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='estimate',
            name='customer_notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='estimate',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='estimate',
            name='estimate',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='estimate',
            name='expiry_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='estimate',
            name='gst_treatment',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='estimate',
            name='igst',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='estimate',
            name='place_of_supply',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='estimate',
            name='project_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='estimate',
            name='reference',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='estimate',
            name='round_off',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='estimate',
            name='sales_person',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='estimate',
            name='sgst',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='estimate',
            name='shippingAddress',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='estimate',
            name='sub_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='estimate',
            name='terms_condition',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='estimate',
            name='total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='estimate_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Estimate_transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_details', models.CharField(default='', max_length=250)),
                ('quantity', models.IntegerField(default=1.0)),
                ('rate', models.FloatField(default=0.0)),
                ('tax', models.CharField(default='', max_length=100)),
                ('amount', models.FloatField(default=0.0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimate.Estimate')),
            ],
        ),
    ]
