# Generated by Django 3.1 on 2020-08-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.CharField(max_length=20)),
                ('expense_account', models.CharField(max_length=100)),
                ('expense_type', models.CharField(max_length=50)),
                ('expense_sac', models.CharField(max_length=200)),
                ('expense_amount', models.CharField(max_length=100)),
                ('expense_paid', models.CharField(max_length=200)),
                ('expense_vendor', models.CharField(max_length=200)),
                ('expense_gst', models.CharField(max_length=200)),
                ('expense_destination', models.CharField(max_length=200)),
                ('expense_rev_charge', models.BooleanField()),
                ('expense_tax', models.CharField(max_length=100)),
                ('expense_invoice', models.CharField(max_length=100)),
                ('expense_notes', models.TextField()),
                ('customer_name', models.CharField(max_length=250)),
                ('expense_file', models.FileField(upload_to='file')),
            ],
        ),
    ]
