# Generated by Django 3.1 on 2020-09-03 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20200831_1943'),
        ('expenses', '0002_auto_20200831_2254'),
    ]

    operations = [
    ]
