# Generated by Django 3.0.8 on 2020-09-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_expenses_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='user',
        ),
        migrations.AddField(
            model_name='expenses',
            name='organisation',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
