# Generated by Django 3.0.8 on 2020-09-29 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200929_1306'),
        ('expenses', '0006_auto_20200925_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Organisation'),
        ),
    ]
