# Generated by Django 3.1 on 2020-08-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('units', models.CharField(max_length=200)),
                ('hsncode', models.CharField(max_length=200)),
                ('taxpreference', models.CharField(max_length=200)),
                ('sellamount', models.CharField(max_length=200)),
                ('salesacc', models.CharField(max_length=15)),
                ('salesdes', models.CharField(max_length=15)),
                ('puramount', models.CharField(max_length=200)),
                ('purchaseacc', models.CharField(max_length=200)),
                ('purchasedes', models.CharField(max_length=200)),
                ('intrastate', models.CharField(max_length=200)),
                ('interstate', models.CharField(max_length=200)),
            ],
        ),
    ]
