# Generated by Django 3.1 on 2020-09-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='hsncode',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='interstate',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='intrastate',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='puramount',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchaseacc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchasedes',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='salesacc',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='salesdes',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sellamount',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='taxpreference',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='units',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
