# Generated by Django 3.0.8 on 2020-09-29 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_logo', models.ImageField(upload_to='uploads/')),
                ('organisation_name', models.CharField(default='', max_length=200)),
                ('industry', models.CharField(default='', max_length=200)),
                ('business_location', models.CharField(default='', max_length=200)),
                ('company_address1', models.CharField(default='', max_length=200)),
                ('company_address2', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('state', models.CharField(default='', max_length=200)),
                ('zipcode', models.CharField(default='', max_length=200)),
                ('fax', models.CharField(default='', max_length=200)),
                ('ph_no', models.CharField(default='', max_length=200)),
                ('Company_ID', models.CharField(default='', max_length=200)),
                ('Tax_ID', models.CharField(default='', max_length=200)),
                ('website', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(default='', max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Organisation'),
        ),
    ]
