# Generated by Django 3.0.8 on 2020-09-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200929_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='state',
            field=models.CharField(default='', max_length=200),
        ),
    ]
