# Generated by Django 3.0.8 on 2020-09-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200929_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='state',
            field=models.CharField(choices=[('andamanandnicobar Islands', 'Andaman and Nicobar Islands'), ('arunachalpradesh', 'Arunachal Pradesh'), ('assam', 'Assam'), ('bihar', 'Bihar'), ('chandigarh', 'Chandigarh'), ('chhattisgarh', 'Chhattisgarh'), ('dadra', 'Dadra and Nagar Haveli and Daman and Diu'), ('delhi', 'Delhi'), ('goa', 'Goa'), ('gujarat', 'Gujarat'), ('haryana', 'Haryana'), ('himachal', 'Himachal Pradesh'), ('jammu', 'Jammu and Kashmir'), ('jhar', 'Jharkhand'), ('kar', 'Karnataka'), ('ker', 'Kerala'), ('ladakh', 'Ladakh'), ('lak', 'Lakshadweep'), ('madh', 'Madhya Pradesh'), ('maha', 'Maharashtra'), ('mani', 'Manipur'), ('mizo', 'Mizoram'), ('naga', 'Nagaland'), ('odi', 'Odisha'), ('puducherry', 'Puducherry'), ('punjab', 'Punjab'), ('rajas', 'Rajasthan'), ('sikkim', 'Sikkim'), ('tamilnadu', 'Tamil Nadu'), ('tel', 'Telangana'), ('tri', 'Tripura'), ('uttar', 'Uttar Pradesh'), ('uttarkhand', 'Uttarakhand'), ('westbengal', 'West Bengal')], default='tamilnadu', max_length=200),
        ),
    ]
