# Generated by Django 3.1 on 2020-09-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200929_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='company_address2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
