# Generated by Django 3.1 on 2020-08-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('billingAddress', models.TextField()),
                ('shippingAddress', models.TextField()),
                ('gst_treatment', models.CharField(max_length=200)),
                ('place_of_supply', models.CharField(max_length=200)),
                ('invoice', models.CharField(max_length=200)),
                ('order_no', models.CharField(max_length=200)),
                ('invoice_date', models.CharField(max_length=30)),
                ('terms', models.CharField(max_length=100)),
                ('due_date', models.CharField(max_length=30)),
                ('sales_person', models.CharField(max_length=100)),
            ],
        ),
    ]
