# Generated by Django 3.1 on 2020-09-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='adjustments',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='attach_file',
            field=models.FileField(default='', upload_to='file'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cgst',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_notes',
            field=models.TextField(default=0.0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='igst',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='item_details',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='invoice',
            name='quantity',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='round_off',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sgst',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sub_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='terms_condition',
            field=models.TextField(default=0.0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
