# Generated by Django 3.0.8 on 2020-09-16 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20200901_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='item_details',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax',
        ),
        migrations.CreateModel(
            name='Invoice_transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_details', models.CharField(default='', max_length=250)),
                ('quantity', models.IntegerField(default=1.0)),
                ('rate', models.FloatField(default=0.0)),
                ('tax', models.CharField(default='', max_length=100)),
                ('amount', models.FloatField(default=0.0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Invoice')),
            ],
        ),
    ]
