# Generated by Django 3.0.8 on 2020-09-16 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_auto_20200916_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='adjustments',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='attach_file',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='billingAddress',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='cgst',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer_notes',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='gst_treatment',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='igst',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='place_of_supply',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='round_off',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='sales_person',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='sgst',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='shippingAddress',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='terms',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='terms_condition',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total',
        ),
    ]
