# Generated by Django 3.0.8 on 2020-09-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_auto_20200916_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='adjustments',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billingAddress',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cgst',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_notes',
            field=models.TextField(default=0.0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='gst_treatment',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='igst',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='place_of_supply',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='round_off',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sales_person',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sgst',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shippingAddress',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sub_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='terms',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='terms_condition',
            field=models.TextField(default=0.0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order_no',
            field=models.CharField(default='', max_length=200),
        ),
    ]
