# Generated by Django 3.0.8 on 2020-09-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_auto_20200918_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='billingAddress',
            new_name='ShippingCity',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='shippingAddress',
            new_name='ShippingState',
        ),
        migrations.AddField(
            model_name='invoice',
            name='ShippingStreet',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ShippingZipcode',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billingCity',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billingState',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billingStreet',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billingZipcode',
            field=models.TextField(default=''),
        ),
    ]
