# Generated by Django 3.0.8 on 2020-09-18 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_auto_20200918_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='ShippingCity',
            new_name='shippingCity',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='ShippingState',
            new_name='shippingState',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='ShippingStreet',
            new_name='shippingStreet',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='ShippingZipcode',
            new_name='shippingZipcode',
        ),
    ]
