# Generated by Django 3.1 on 2020-09-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('billingAddress', models.TextField()),
                ('shippingAddress', models.TextField()),
                ('gst_treatment', models.CharField(max_length=200)),
                ('place_of_supply', models.CharField(max_length=200)),
                ('sales_order', models.CharField(max_length=200)),
                ('reference', models.CharField(max_length=200)),
                ('sales_date', models.CharField(max_length=30)),
                ('shipment_date', models.CharField(max_length=30)),
                ('payment_terms', models.CharField(max_length=100)),
                ('delivery_method', models.CharField(max_length=100)),
                ('sales_person', models.CharField(max_length=100)),
                ('item_details', models.CharField(default='', max_length=250)),
                ('quantity', models.FloatField(default=1.0)),
                ('rate', models.FloatField(default=0.0)),
                ('tax', models.CharField(default='', max_length=100)),
                ('amount', models.FloatField(default=0.0)),
                ('sub_total', models.FloatField(default=0.0)),
                ('cgst', models.FloatField(default=0.0)),
                ('sgst', models.FloatField(default=0.0)),
                ('igst', models.FloatField(default=0.0)),
                ('discount', models.FloatField(default=0.0)),
                ('adjustments', models.FloatField(default=0.0)),
                ('round_off', models.FloatField(default=0.0)),
                ('total', models.FloatField(default=0.0)),
                ('customer_notes', models.TextField(default=0.0)),
                ('terms_condition', models.TextField(default=0.0)),
                ('attach_file', models.FileField(default='', upload_to='file')),
            ],
        ),
    ]
